version: "3"
services:
  server:
    image: contributionls/utils-server
    restart: always
    environment:
      VIRTUAL_HOST: api.utils.men
      LETSENCRYPT_HOST: api.utils.men
  merge-client:
    image: contributionls/utils-merge-client
    environment:
      REACT_APP_API_HOST: "https://api.utils.men"
      VIRTUAL_HOST: merge.utils.men
      LETSENCRYPT_HOST: merge.utils.men
    restart: always
  convert-client:
    image: contributionls/utils-convert-client
    environment:
      REACT_APP_API_HOST: "https://api.utils.men"
      VIRTUAL_HOST: convert.utils.men
      LETSENCRYPT_HOST: convert.utils.men
    restart: always
  jsonpath-client:
    image: contributionls/utils-jsonpath-client
    environment:
      REACT_APP_API_HOST: "https://api.utils.men"
      VIRTUAL_HOST: jsonpath.utils.men
      LETSENCRYPT_HOST: jsonpath.utils.men
    restart: always
  home-client:
    image: contributionls/utils-home-client
    restart: always
    environment:
      VIRTUAL_HOST: utils.men
      LETSENCRYPT_HOST: utils.men
networks:
  default:
    external:
      name: nginx-proxy
